//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Monitor.rc 使用
//
#define ID_BTN_CANCEL_ALL               3
#define ID_BTN_SELECT_ALL               4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MONITOR_FORM                101
#define IDR_MAINFRAME                   128
#define IDR_MonitorTYPE                 130
#define IDD_DSCONF                      310
#define IDD_GWCONF                      311
#define IDD_PROCONF                     312
#define IDD_PRJCONF                     312
#define IDD_TIME_CHECK                  313
#define IDD_SOUND_CHOICE                314
#define IDD_SOUND_CHANGE                314
#define IDD_HISTORY                     315
#define IDB_SENSORBMP                   316
#define IDB_BITMAP1                     318
#define IDB_GWBMP                       318
#define IDC_STC_DATARV                  1000
#define IDC_STC_DATASRVx                1001
#define IDC_STC_DATARV2                 1002
#define IDC_STC_DATASRVx2               1003
#define IDC_STC_DATASRVx3               1004
#define IDC_STC_DATASRVx4               1005
#define IDC_STC_DATASRVx5               1006
#define IDC_STC_DATASRVx6               1007
#define IDC_STC_DATASRVx7               1008
#define IDC_STC_DATARV3                 1009
#define IDC_STC_DATARV4                 1010
#define IDC_STC_DATARV5                 1011
#define IDC_STC_DATARV6                 1012
#define IDC_STC_DATARV7                 1013
#define IDC_STC_DATARV8                 1014
#define IDC_STC_DATASRVx8               1015
#define IDC_TREE_ADDR                   1016
#define IDC_BTN_BEGINCTRL               1017
#define IDC_BTN_CHKSET                  1018
#define IDC_BTN_SILENT                  1019
#define IDC_BTN_RESET                   1020
#define IDC_BTN_NETDATA                 1021
#define IDC_BTN_CLR                     1022
#define IDC_GRB_PROALARM                1023
#define IDC_STC_FIREALARM               1024
#define IDC_STC_FIREALARMx1             1025
#define IDC_STC_FIREALARMx2             1026
#define IDC_STC_FIRPROX2                1027
#define IDC_STC_FIRPRO                  1028
#define IDC_STC_FIRPROX1                1029
#define IDC_PIC_MAP                     1030
#define IDC_LIST1                       1031
#define IDC_LISTCTRL                    1031
#define IDC_LISTCTRL_NUM                1031
#define IDC_LISTCTRL_LOC                1031
#define IDC_LIST_CTRL_TIMECHECK         1031
#define IDC_LIST_CTRL_HIS               1031
#define IDC_BTN_CANCEL                  1032
#define IDC_STC_DS_LIST                 1033
#define IDC_BTN_DELETE                  1034
#define IDC_BTN_SAVE                    1035
#define IDC_BTN_ADD                     1036
#define IDC_EDIT_ADD                    1037
#define ID_BTN_SAVE                     1038
#define IDC_BTN_CANCEL_ALL              1039
#define IDC_BTN_SELECT_ALL              1040
#define IDC_BTN_CHECK                   1043
#define IDC_LISTCTRL_NGSTATE            1044
#define IDC_STC_NGSTATE                 1045
#define IDC_BTN_PROSV                   1046
#define IDC_BTN_PRJAVE                  1046
#define IDC_BTN_PRJSAVE                 1046
#define ID_BTN_PROLD                    1047
#define ID_BTN_PRJLOAD                  1047
#define ID_BTN_OK                       1048
#define IDC_STC_LCINFO                  1049
#define IDC_BTN_LKNG                    1050
#define IDC_BTN_GWDATA                  1050
#define IDC_BTN_ADDNG                   1051
#define IDC_BTN_ADDGW                   1051
#define IDC_BTN_ADDDV                   1052
#define IDC_BTN_ADDSENSOR               1052
#define IDC_STC_ARNM                    1053
#define IDC_COMBO_ARNM                  1054
#define IDC_COMBO_AREA                  1054
#define IDC_COMBO_NGNO                  1055
#define IDC_COMBO_GWID                  1055
#define IDC_STC_NGNO                    1056
#define ID_BTN_PROLD2                   1057
#define IDC_LIST_BOX_NGNO               1058
#define IDC_LISTBOX_SENSOR              1058
#define IDC_STC_PICINFO                 1059
#define IDC_PIC_CTRL                    1060
#define ID_BTN_BEGIN_CHECK              1061
#define ID_BTN_CNACEL                   1062
#define ID_BTN_CANCEL                   1063
#define IDC_STC_PREALM3                 1065
#define IDC_BTN_CHG1                    1066
#define IDC_STC_PREALM2                 1067
#define IDC_STC_PREALM1                 1068
#define IDC_STC_PRO                     1069
#define IDC_STC_ALARMX                  1070
#define IDC_BTN_CHG2                    1071
#define IDC_BTN_CHG3                    1072
#define IDC_BTN_CHG4                    1073
#define IDC_BTN_CHG5                    1074
#define IDC_STC_ALRAM                   1075
#define IDC_STC_PREALARMX3              1076
#define IDC_BTN_SRCH                    1076
#define IDC_STC_PREALARMX2              1078
#define IDC_BTN_DIP_ALL                 1078
#define IDC_STC_PREALARMX1              1079
#define IDC_DATETIMEPICKER_DATE1        1079
#define IDC_STC_PROX                    1080
#define IDC_DATETIMEPICKER_TIME1        1080
#define IDC_DATETIMEPICKER_DATE2        1081
#define IDC_DATETIMEPICKER_TIME2        1082
#define IDC_COMBO_EVENT                 1083
#define IDC_COMBO_ASD_NO                1084
#define IDC_STC_TM_SCALE                1085
#define IDC_STC_ASD_NO                  1086
#define IDC_STC_THREAD                  1087
#define IDC_STC_EVT_CLASS               1088
#define IDC_TREE1                       1089
#define IDC_PRJ_TREE_MAPLIST            1089
#define ID_32771                        32771
#define ID_MENU_SRVCONF                 32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_MENU_NG                      32778
#define ID_MENU_NGCONF                  32779
#define ID_MENU_PROCONF                 32780
#define ID_MENU_TCHK                    32781
#define ID_MENU_SOUND                   32782
#define ID_MENU_TMCHK                   32783
#define ID_MENU_HISTORY                 32784
#define ID_MENU_GWCONF                  32785
#define ID_MENU_PRJCONF                 32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        319
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
